package com.greenrobot.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.download.myapplication.HLSOffline;

import com.greenrobot.greendao.HLSOfflineDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hLSOfflineDaoConfig;

    private final HLSOfflineDao hLSOfflineDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hLSOfflineDaoConfig = daoConfigMap.get(HLSOfflineDao.class).clone();
        hLSOfflineDaoConfig.initIdentityScope(type);

        hLSOfflineDao = new HLSOfflineDao(hLSOfflineDaoConfig, this);

        registerDao(HLSOffline.class, hLSOfflineDao);
    }
    
    public void clear() {
        hLSOfflineDaoConfig.clearIdentityScope();
    }

    public HLSOfflineDao getHLSOfflineDao() {
        return hLSOfflineDao;
    }

}
